var teamsData = [
    {
        "name": "HNK Hajduk Split",
        "location": "Split",
        "stadium": "Poljud",
        "wins": 21,
        "draws": 9,
        "losses": 6,
        "totalplayers": 44,
        "nationalteamplayers": 2,
        "foreignplayers": 13,
        "goals": 64,
        "goalsconceded": 31,
        "possessionpercentage": 55.8,
        "cleansheets": 18
    },
    {
        "name": "NK Osijek",
        "location": "Osijek",
        "stadium": "Gradski Vrt",
        "wins": 19,
        "draws": 12,
        "losses": 5,
        "totalplayers": 31,
        "nationalteamplayers": 4,
        "foreignplayers": 9,
        "goals": 49,
        "goalsconceded": 29,
        "possessionpercentage": 49.2,
        "cleansheets": 17
    },
    {
        "name": "GNK Dinamo Zagreb",
        "location": "Zagreb",
        "stadium": "Maksimir",
        "wins": 24,
        "draws": 7,
        "losses": 5,
        "totalplayers": 46,
        "nationalteamplayers": 10,
        "foreignplayers": 16,
        "goals": 68,
        "goalsconceded": 22,
        "possessionpercentage": 62.6,
        "cleansheets": 20
    },
    {
        "name": "NK Rijeka",
        "location": "Rijeka",
        "stadium": "Rujevica",
        "wins": 20,
        "draws": 5,
        "losses": 11,
        "totalplayers": 31,
        "nationalteamplayers": 3,
        "foreignplayers": 17,
        "goals": 71,
        "goalsconceded": 51,
        "possessionpercentage": 53.3,
        "cleansheets": 9
    },
    {
        "name": "HNK Gorica",
        "location": "Velika Gorica",
        "stadium": "Gradski stadion Velika Gorica",
        "wins": 12,
        "draws": 9,
        "losses": 15,
        "totalplayers": 29,
        "nationalteamplayers": 1,
        "foreignplayers": 14,
        "goals": 43,
        "goalsconceded": 50,
        "possessionpercentage": 48.6,
        "cleansheets": 9
    },
    {
        "name": "NK Lokomotiva",
        "location": "Zagreb",
        "stadium": "Kranjceviceva",
        "wins": 12,
        "draws": 13,
        "losses": 11,
        "totalplayers": 39,
        "nationalteamplayers": 1,
        "foreignplayers": 15,
        "goals": 55,
        "goalsconceded": 50,
        "possessionpercentage": 51.1,
        "cleansheets": 6
    },
    {
        "name": "NK Slaven Belupo",
        "location": "Koprivnica",
        "stadium": "Gradski stadion Ivan Kusek Apas",
        "wins": 9,
        "draws": 9,
        "losses": 18,
        "totalplayers": 29,
        "nationalteamplayers": 1,
        "foreignplayers": 8,
        "goals": 35,
        "goalsconceded": 54,
        "possessionpercentage": 46.3,
        "cleansheets": 6
    },
    {
        "name": "HNK Sibenik",
        "location": "Sibenik",
        "stadium": "Subicevac",
        "wins": 9,
        "draws": 5,
        "losses": 22,
        "totalplayers": 34,
        "nationalteamplayers": 0,
        "foreignplayers": 15,
        "goals": 46,
        "goalsconceded": 75,
        "possessionpercentage": 42.8,
        "cleansheets": 1
    },
    {
        "name": "NK Istra 1961",
        "location": "Pula",
        "stadium": "Aldo Drosina",
        "wins": 7,
        "draws": 10,
        "losses": 19,
        "totalplayers": 29,
        "nationalteamplayers": 2,
        "foreignplayers": 14,
        "goals": 42,
        "goalsconceded": 67,
        "possessionpercentage": 51.8,
        "cleansheets": 5
    },
    {
        "name": "NK Hrvatski Dragovoljac",
        "location": "Zagreb",
        "stadium": "Stadion NSC Stjepan Spajić",
        "wins": 4,
        "draws": 7,
        "losses": 25,
        "totalplayers": 33,
        "nationalteamplayers": 0,
        "foreignplayers": 6,
        "goals": 31,
        "goalsconceded": 75,
        "possessionpercentage": 38.5,
        "cleansheets": 3
    }
];

var leagueDataBySeasons =
    [
        {
            "seasonyear": "2021./22.",
            "matchesplayed": 180,
            "hometeamwins": 77,
            "draws": 43,
            "awayteamwins": 60,
            "goalsscored": 504,
            "homegoals": 272,
            "awaygoals": 232
        },
        {
            "seasonyear": "2020./21.",
            "matchesplayed": 180,
            "hometeamwins": 73,
            "draws": 42,
            "awayteamwins": 65,
            "goalsscored": 456,
            "homegoals": 237,
            "awaygoals": 219
        },
        {
            "seasonyear": "2019./20.",
            "matchesplayed": 180,
            "hometeamwins": 91,
            "draws": 43,
            "awayteamwins": 46,
            "goalsscored": 450,
            "homegoals": 263,
            "awaygoals": 187
        }
    ];
