var teamsData = [
    {
        "name": "HNK Hajduk Split",
        "wins": 21,
        "draws": 9,
        "losses": 6,
        "totalplayers": 56,
        "nationalteamplayers": 3,
        "foreignplayers": 16,
        "goals": 64,
        "goalsconceded": 31,
        "cleansheets": 18
    },
    {
        "name": "NK Osijek",
        "wins": 19,
        "draws": 12,
        "losses": 5,
        "totalplayers": 33,
        "nationalteamplayers": 4,
        "foreignplayers": 10,
        "goals": 49,
        "goalsconceded": 29,
        "cleansheets": 17
    },
    {
        "name": "GNK Dinamo Zagreb",
        "wins": 24,
        "draws": 7,
        "losses": 5,
        "totalplayers": 44,
        "nationalteamplayers": 11,
        "foreignplayers": 16,
        "goals": 68,
        "goalsconceded": 22,
        "cleansheets": 20
    },
    {
        "name": "NK Rijeka",
        "wins": 20,
        "draws": 5,
        "losses": 11,
        "totalplayers": 37,
        "nationalteamplayers": 4,
        "foreignplayers": 17,
        "goals": 71,
        "goalsconceded": 51,
        "cleansheets": 9
    },
    {
        "name": "HNK Gorica",
        "wins": 12,
        "draws": 9,
        "losses": 15,
        "totalplayers": 29,
        "nationalteamplayers": 1,
        "foreignplayers": 14,
        "goals": 43,
        "goalsconceded": 50,
        "cleansheets": 9
    },
    {
        "name": "NK Lokomotiva",
        "wins": 12,
        "draws": 13,
        "losses": 11,
        "totalplayers": 39,
        "nationalteamplayers": 1,
        "foreignplayers": 15,
        "goals": 55,
        "goalsconceded": 50,
        "cleansheets": 6
    },
    {
        "name": "NK Slaven Belupo",
        "wins": 9,
        "draws": 9,
        "losses": 18,
        "totalplayers": 29,
        "nationalteamplayers": 1,
        "foreignplayers": 8,
        "goals": 35,
        "goalsconceded": 54,
        "cleansheets": 6
    },
    {
        "name": "HNK Sibenik",
        "wins": 9,
        "draws": 5,
        "losses": 22,
        "totalplayers": 34,
        "nationalteamplayers": 0,
        "foreignplayers": 15,
        "goals": 46,
        "goalsconceded": 75,
        "cleansheets": 1
    },
    {
        "name": "NK Istra 1961",
        "wins": 7,
        "draws": 10,
        "losses": 19,
        "totalplayers": 29,
        "nationalteamplayers": 2,
        "foreignplayers": 14,
        "goals": 42,
        "goalsconceded": 67,
        "cleansheets": 5
    },
    {
        "name": "NK Hrvatski Dragovoljac",
        "wins": 4,
        "draws": 7,
        "losses": 25,
        "totalplayers": 33,
        "nationalteamplayers": 0,
        "foreignplayers": 6,
        "goals": 31,
        "goalsconceded": 75,
        "cleansheets": 3
    }
];
